// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.3
// source: packets.proto

package packets

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginRequestMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequestMessage) Reset() {
	*x = LoginRequestMessage{}
	mi := &file_packets_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequestMessage) ProtoMessage() {}

func (x *LoginRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequestMessage.ProtoReflect.Descriptor instead.
func (*LoginRequestMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequestMessage) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequestMessage) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterRequestMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequestMessage) Reset() {
	*x = RegisterRequestMessage{}
	mi := &file_packets_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequestMessage) ProtoMessage() {}

func (x *RegisterRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequestMessage.ProtoReflect.Descriptor instead.
func (*RegisterRequestMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterRequestMessage) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequestMessage) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type OKResponseMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OKResponseMessage) Reset() {
	*x = OKResponseMessage{}
	mi := &file_packets_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OKResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OKResponseMessage) ProtoMessage() {}

func (x *OKResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OKResponseMessage.ProtoReflect.Descriptor instead.
func (*OKResponseMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{2}
}

type DenyResponseMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DenyResponseMessage) Reset() {
	*x = DenyResponseMessage{}
	mi := &file_packets_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DenyResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DenyResponseMessage) ProtoMessage() {}

func (x *DenyResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DenyResponseMessage.ProtoReflect.Descriptor instead.
func (*DenyResponseMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{3}
}

func (x *DenyResponseMessage) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type LoginSuccessMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Uid           uint32                 `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginSuccessMessage) Reset() {
	*x = LoginSuccessMessage{}
	mi := &file_packets_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginSuccessMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginSuccessMessage) ProtoMessage() {}

func (x *LoginSuccessMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginSuccessMessage.ProtoReflect.Descriptor instead.
func (*LoginSuccessMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{4}
}

func (x *LoginSuccessMessage) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginSuccessMessage) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type PlayerEnterAreaRequestMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AreaName      string                 `protobuf:"bytes,1,opt,name=area_name,json=areaName,proto3" json:"area_name,omitempty"`
	EntranceId    uint32                 `protobuf:"varint,2,opt,name=entrance_id,json=entranceId,proto3" json:"entrance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerEnterAreaRequestMessage) Reset() {
	*x = PlayerEnterAreaRequestMessage{}
	mi := &file_packets_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerEnterAreaRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerEnterAreaRequestMessage) ProtoMessage() {}

func (x *PlayerEnterAreaRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerEnterAreaRequestMessage.ProtoReflect.Descriptor instead.
func (*PlayerEnterAreaRequestMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{5}
}

func (x *PlayerEnterAreaRequestMessage) GetAreaName() string {
	if x != nil {
		return x.AreaName
	}
	return ""
}

func (x *PlayerEnterAreaRequestMessage) GetEntranceId() uint32 {
	if x != nil {
		return x.EntranceId
	}
	return 0
}

type PlayerEnterAreaMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	X             float32                `protobuf:"fixed32,3,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,4,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerEnterAreaMessage) Reset() {
	*x = PlayerEnterAreaMessage{}
	mi := &file_packets_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerEnterAreaMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerEnterAreaMessage) ProtoMessage() {}

func (x *PlayerEnterAreaMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerEnterAreaMessage.ProtoReflect.Descriptor instead.
func (*PlayerEnterAreaMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{6}
}

func (x *PlayerEnterAreaMessage) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *PlayerEnterAreaMessage) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PlayerEnterAreaMessage) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type PlayerLeaveAreaMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerLeaveAreaMessage) Reset() {
	*x = PlayerLeaveAreaMessage{}
	mi := &file_packets_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerLeaveAreaMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerLeaveAreaMessage) ProtoMessage() {}

func (x *PlayerLeaveAreaMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerLeaveAreaMessage.ProtoReflect.Descriptor instead.
func (*PlayerLeaveAreaMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{7}
}

type PlayerMoveMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromX         float32                `protobuf:"fixed32,1,opt,name=from_x,json=fromX,proto3" json:"from_x,omitempty"`
	FromY         float32                `protobuf:"fixed32,2,opt,name=from_y,json=fromY,proto3" json:"from_y,omitempty"`
	ToX           float32                `protobuf:"fixed32,3,opt,name=to_x,json=toX,proto3" json:"to_x,omitempty"`
	ToY           float32                `protobuf:"fixed32,4,opt,name=to_y,json=toY,proto3" json:"to_y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerMoveMessage) Reset() {
	*x = PlayerMoveMessage{}
	mi := &file_packets_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerMoveMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerMoveMessage) ProtoMessage() {}

func (x *PlayerMoveMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerMoveMessage.ProtoReflect.Descriptor instead.
func (*PlayerMoveMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{8}
}

func (x *PlayerMoveMessage) GetFromX() float32 {
	if x != nil {
		return x.FromX
	}
	return 0
}

func (x *PlayerMoveMessage) GetFromY() float32 {
	if x != nil {
		return x.FromY
	}
	return 0
}

func (x *PlayerMoveMessage) GetToX() float32 {
	if x != nil {
		return x.ToX
	}
	return 0
}

func (x *PlayerMoveMessage) GetToY() float32 {
	if x != nil {
		return x.ToY
	}
	return 0
}

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Type          uint32                 `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"` // 记录当前聊天内容的类型，0为当前区域，1为全局
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_packets_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{9}
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatMessage) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ChatMessage) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

type Packet struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Uid   uint32                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	// Types that are valid to be assigned to Msg:
	//
	//	*Packet_LoginRequest
	//	*Packet_RegisterRequest
	//	*Packet_OkResponse
	//	*Packet_DenyResponse
	//	*Packet_LoginSuccess
	//	*Packet_PlayerEnter
	//	*Packet_PlayerLeave
	//	*Packet_PlayerMovement
	//	*Packet_PlayerEnterRequest
	//	*Packet_Chat
	Msg           isPacket_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Packet) Reset() {
	*x = Packet{}
	mi := &file_packets_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{10}
}

func (x *Packet) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Packet) GetMsg() isPacket_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *Packet) GetLoginRequest() *LoginRequestMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_LoginRequest); ok {
			return x.LoginRequest
		}
	}
	return nil
}

func (x *Packet) GetRegisterRequest() *RegisterRequestMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_RegisterRequest); ok {
			return x.RegisterRequest
		}
	}
	return nil
}

func (x *Packet) GetOkResponse() *OKResponseMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_OkResponse); ok {
			return x.OkResponse
		}
	}
	return nil
}

func (x *Packet) GetDenyResponse() *DenyResponseMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_DenyResponse); ok {
			return x.DenyResponse
		}
	}
	return nil
}

func (x *Packet) GetLoginSuccess() *LoginSuccessMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_LoginSuccess); ok {
			return x.LoginSuccess
		}
	}
	return nil
}

func (x *Packet) GetPlayerEnter() *PlayerEnterAreaMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_PlayerEnter); ok {
			return x.PlayerEnter
		}
	}
	return nil
}

func (x *Packet) GetPlayerLeave() *PlayerLeaveAreaMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_PlayerLeave); ok {
			return x.PlayerLeave
		}
	}
	return nil
}

func (x *Packet) GetPlayerMovement() *PlayerMoveMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_PlayerMovement); ok {
			return x.PlayerMovement
		}
	}
	return nil
}

func (x *Packet) GetPlayerEnterRequest() *PlayerEnterAreaRequestMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_PlayerEnterRequest); ok {
			return x.PlayerEnterRequest
		}
	}
	return nil
}

func (x *Packet) GetChat() *ChatMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_Chat); ok {
			return x.Chat
		}
	}
	return nil
}

type isPacket_Msg interface {
	isPacket_Msg()
}

type Packet_LoginRequest struct {
	LoginRequest *LoginRequestMessage `protobuf:"bytes,2,opt,name=login_request,json=loginRequest,proto3,oneof"`
}

type Packet_RegisterRequest struct {
	RegisterRequest *RegisterRequestMessage `protobuf:"bytes,3,opt,name=register_request,json=registerRequest,proto3,oneof"`
}

type Packet_OkResponse struct {
	OkResponse *OKResponseMessage `protobuf:"bytes,4,opt,name=ok_response,json=okResponse,proto3,oneof"`
}

type Packet_DenyResponse struct {
	DenyResponse *DenyResponseMessage `protobuf:"bytes,5,opt,name=deny_response,json=denyResponse,proto3,oneof"`
}

type Packet_LoginSuccess struct {
	LoginSuccess *LoginSuccessMessage `protobuf:"bytes,6,opt,name=login_success,json=loginSuccess,proto3,oneof"`
}

type Packet_PlayerEnter struct {
	PlayerEnter *PlayerEnterAreaMessage `protobuf:"bytes,7,opt,name=player_enter,json=playerEnter,proto3,oneof"`
}

type Packet_PlayerLeave struct {
	PlayerLeave *PlayerLeaveAreaMessage `protobuf:"bytes,8,opt,name=player_leave,json=playerLeave,proto3,oneof"`
}

type Packet_PlayerMovement struct {
	PlayerMovement *PlayerMoveMessage `protobuf:"bytes,9,opt,name=player_movement,json=playerMovement,proto3,oneof"`
}

type Packet_PlayerEnterRequest struct {
	PlayerEnterRequest *PlayerEnterAreaRequestMessage `protobuf:"bytes,10,opt,name=player_enter_request,json=playerEnterRequest,proto3,oneof"`
}

type Packet_Chat struct {
	Chat *ChatMessage `protobuf:"bytes,11,opt,name=chat,proto3,oneof"`
}

func (*Packet_LoginRequest) isPacket_Msg() {}

func (*Packet_RegisterRequest) isPacket_Msg() {}

func (*Packet_OkResponse) isPacket_Msg() {}

func (*Packet_DenyResponse) isPacket_Msg() {}

func (*Packet_LoginSuccess) isPacket_Msg() {}

func (*Packet_PlayerEnter) isPacket_Msg() {}

func (*Packet_PlayerLeave) isPacket_Msg() {}

func (*Packet_PlayerMovement) isPacket_Msg() {}

func (*Packet_PlayerEnterRequest) isPacket_Msg() {}

func (*Packet_Chat) isPacket_Msg() {}

var File_packets_proto protoreflect.FileDescriptor

const file_packets_proto_rawDesc = "" +
	"\n" +
	"\rpackets.proto\x12\apackets\"M\n" +
	"\x13LoginRequestMessage\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"P\n" +
	"\x16RegisterRequestMessage\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x13\n" +
	"\x11OKResponseMessage\"-\n" +
	"\x13DenyResponseMessage\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"C\n" +
	"\x13LoginSuccessMessage\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\rR\x03uid\"]\n" +
	"\x1dPlayerEnterAreaRequestMessage\x12\x1b\n" +
	"\tarea_name\x18\x01 \x01(\tR\bareaName\x12\x1f\n" +
	"\ventrance_id\x18\x02 \x01(\rR\n" +
	"entranceId\"P\n" +
	"\x16PlayerEnterAreaMessage\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\f\n" +
	"\x01x\x18\x03 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x04 \x01(\x02R\x01y\"\x18\n" +
	"\x16PlayerLeaveAreaMessage\"g\n" +
	"\x11PlayerMoveMessage\x12\x15\n" +
	"\x06from_x\x18\x01 \x01(\x02R\x05fromX\x12\x15\n" +
	"\x06from_y\x18\x02 \x01(\x02R\x05fromY\x12\x11\n" +
	"\x04to_x\x18\x03 \x01(\x02R\x03toX\x12\x11\n" +
	"\x04to_y\x18\x04 \x01(\x02R\x03toY\"W\n" +
	"\vChatMessage\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x12\n" +
	"\x04type\x18\x03 \x01(\rR\x04type\"\xd8\x05\n" +
	"\x06Packet\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\rR\x03uid\x12C\n" +
	"\rlogin_request\x18\x02 \x01(\v2\x1c.packets.LoginRequestMessageH\x00R\floginRequest\x12L\n" +
	"\x10register_request\x18\x03 \x01(\v2\x1f.packets.RegisterRequestMessageH\x00R\x0fregisterRequest\x12=\n" +
	"\vok_response\x18\x04 \x01(\v2\x1a.packets.OKResponseMessageH\x00R\n" +
	"okResponse\x12C\n" +
	"\rdeny_response\x18\x05 \x01(\v2\x1c.packets.DenyResponseMessageH\x00R\fdenyResponse\x12C\n" +
	"\rlogin_success\x18\x06 \x01(\v2\x1c.packets.LoginSuccessMessageH\x00R\floginSuccess\x12D\n" +
	"\fplayer_enter\x18\a \x01(\v2\x1f.packets.PlayerEnterAreaMessageH\x00R\vplayerEnter\x12D\n" +
	"\fplayer_leave\x18\b \x01(\v2\x1f.packets.PlayerLeaveAreaMessageH\x00R\vplayerLeave\x12E\n" +
	"\x0fplayer_movement\x18\t \x01(\v2\x1a.packets.PlayerMoveMessageH\x00R\x0eplayerMovement\x12Z\n" +
	"\x14player_enter_request\x18\n" +
	" \x01(\v2&.packets.PlayerEnterAreaRequestMessageH\x00R\x12playerEnterRequest\x12*\n" +
	"\x04chat\x18\v \x01(\v2\x14.packets.ChatMessageH\x00R\x04chatB\x05\n" +
	"\x03msgB\rZ\vpkg/packetsb\x06proto3"

var (
	file_packets_proto_rawDescOnce sync.Once
	file_packets_proto_rawDescData []byte
)

func file_packets_proto_rawDescGZIP() []byte {
	file_packets_proto_rawDescOnce.Do(func() {
		file_packets_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_packets_proto_rawDesc), len(file_packets_proto_rawDesc)))
	})
	return file_packets_proto_rawDescData
}

var file_packets_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_packets_proto_goTypes = []any{
	(*LoginRequestMessage)(nil),           // 0: packets.LoginRequestMessage
	(*RegisterRequestMessage)(nil),        // 1: packets.RegisterRequestMessage
	(*OKResponseMessage)(nil),             // 2: packets.OKResponseMessage
	(*DenyResponseMessage)(nil),           // 3: packets.DenyResponseMessage
	(*LoginSuccessMessage)(nil),           // 4: packets.LoginSuccessMessage
	(*PlayerEnterAreaRequestMessage)(nil), // 5: packets.PlayerEnterAreaRequestMessage
	(*PlayerEnterAreaMessage)(nil),        // 6: packets.PlayerEnterAreaMessage
	(*PlayerLeaveAreaMessage)(nil),        // 7: packets.PlayerLeaveAreaMessage
	(*PlayerMoveMessage)(nil),             // 8: packets.PlayerMoveMessage
	(*ChatMessage)(nil),                   // 9: packets.ChatMessage
	(*Packet)(nil),                        // 10: packets.Packet
}
var file_packets_proto_depIdxs = []int32{
	0,  // 0: packets.Packet.login_request:type_name -> packets.LoginRequestMessage
	1,  // 1: packets.Packet.register_request:type_name -> packets.RegisterRequestMessage
	2,  // 2: packets.Packet.ok_response:type_name -> packets.OKResponseMessage
	3,  // 3: packets.Packet.deny_response:type_name -> packets.DenyResponseMessage
	4,  // 4: packets.Packet.login_success:type_name -> packets.LoginSuccessMessage
	6,  // 5: packets.Packet.player_enter:type_name -> packets.PlayerEnterAreaMessage
	7,  // 6: packets.Packet.player_leave:type_name -> packets.PlayerLeaveAreaMessage
	8,  // 7: packets.Packet.player_movement:type_name -> packets.PlayerMoveMessage
	5,  // 8: packets.Packet.player_enter_request:type_name -> packets.PlayerEnterAreaRequestMessage
	9,  // 9: packets.Packet.chat:type_name -> packets.ChatMessage
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_packets_proto_init() }
func file_packets_proto_init() {
	if File_packets_proto != nil {
		return
	}
	file_packets_proto_msgTypes[10].OneofWrappers = []any{
		(*Packet_LoginRequest)(nil),
		(*Packet_RegisterRequest)(nil),
		(*Packet_OkResponse)(nil),
		(*Packet_DenyResponse)(nil),
		(*Packet_LoginSuccess)(nil),
		(*Packet_PlayerEnter)(nil),
		(*Packet_PlayerLeave)(nil),
		(*Packet_PlayerMovement)(nil),
		(*Packet_PlayerEnterRequest)(nil),
		(*Packet_Chat)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_packets_proto_rawDesc), len(file_packets_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_packets_proto_goTypes,
		DependencyIndexes: file_packets_proto_depIdxs,
		MessageInfos:      file_packets_proto_msgTypes,
	}.Build()
	File_packets_proto = out.File
	file_packets_proto_goTypes = nil
	file_packets_proto_depIdxs = nil
}
