// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.3
// source: shared/packets.proto

package packets

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginRequestMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequestMessage) Reset() {
	*x = LoginRequestMessage{}
	mi := &file_shared_packets_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequestMessage) ProtoMessage() {}

func (x *LoginRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_shared_packets_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequestMessage.ProtoReflect.Descriptor instead.
func (*LoginRequestMessage) Descriptor() ([]byte, []int) {
	return file_shared_packets_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequestMessage) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequestMessage) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterRequestMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequestMessage) Reset() {
	*x = RegisterRequestMessage{}
	mi := &file_shared_packets_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequestMessage) ProtoMessage() {}

func (x *RegisterRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_shared_packets_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequestMessage.ProtoReflect.Descriptor instead.
func (*RegisterRequestMessage) Descriptor() ([]byte, []int) {
	return file_shared_packets_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterRequestMessage) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequestMessage) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type OKResponseMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OKResponseMessage) Reset() {
	*x = OKResponseMessage{}
	mi := &file_shared_packets_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OKResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OKResponseMessage) ProtoMessage() {}

func (x *OKResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_shared_packets_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OKResponseMessage.ProtoReflect.Descriptor instead.
func (*OKResponseMessage) Descriptor() ([]byte, []int) {
	return file_shared_packets_proto_rawDescGZIP(), []int{2}
}

type DenyResponseMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DenyResponseMessage) Reset() {
	*x = DenyResponseMessage{}
	mi := &file_shared_packets_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DenyResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DenyResponseMessage) ProtoMessage() {}

func (x *DenyResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_shared_packets_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DenyResponseMessage.ProtoReflect.Descriptor instead.
func (*DenyResponseMessage) Descriptor() ([]byte, []int) {
	return file_shared_packets_proto_rawDescGZIP(), []int{3}
}

func (x *DenyResponseMessage) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type LoginSuccessMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Uid           uint32                 `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginSuccessMessage) Reset() {
	*x = LoginSuccessMessage{}
	mi := &file_shared_packets_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginSuccessMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginSuccessMessage) ProtoMessage() {}

func (x *LoginSuccessMessage) ProtoReflect() protoreflect.Message {
	mi := &file_shared_packets_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginSuccessMessage.ProtoReflect.Descriptor instead.
func (*LoginSuccessMessage) Descriptor() ([]byte, []int) {
	return file_shared_packets_proto_rawDescGZIP(), []int{4}
}

func (x *LoginSuccessMessage) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginSuccessMessage) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type PlayerEnterAreaRequestMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AreaName      string                 `protobuf:"bytes,1,opt,name=area_name,json=areaName,proto3" json:"area_name,omitempty"`
	EntranceId    uint32                 `protobuf:"varint,2,opt,name=entrance_id,json=entranceId,proto3" json:"entrance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerEnterAreaRequestMessage) Reset() {
	*x = PlayerEnterAreaRequestMessage{}
	mi := &file_shared_packets_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerEnterAreaRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerEnterAreaRequestMessage) ProtoMessage() {}

func (x *PlayerEnterAreaRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_shared_packets_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerEnterAreaRequestMessage.ProtoReflect.Descriptor instead.
func (*PlayerEnterAreaRequestMessage) Descriptor() ([]byte, []int) {
	return file_shared_packets_proto_rawDescGZIP(), []int{5}
}

func (x *PlayerEnterAreaRequestMessage) GetAreaName() string {
	if x != nil {
		return x.AreaName
	}
	return ""
}

func (x *PlayerEnterAreaRequestMessage) GetEntranceId() uint32 {
	if x != nil {
		return x.EntranceId
	}
	return 0
}

type PlayerEnterAreaResponseMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AreaName      string                 `protobuf:"bytes,1,opt,name=area_name,json=areaName,proto3" json:"area_name,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerEnterAreaResponseMessage) Reset() {
	*x = PlayerEnterAreaResponseMessage{}
	mi := &file_shared_packets_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerEnterAreaResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerEnterAreaResponseMessage) ProtoMessage() {}

func (x *PlayerEnterAreaResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_shared_packets_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerEnterAreaResponseMessage.ProtoReflect.Descriptor instead.
func (*PlayerEnterAreaResponseMessage) Descriptor() ([]byte, []int) {
	return file_shared_packets_proto_rawDescGZIP(), []int{6}
}

func (x *PlayerEnterAreaResponseMessage) GetAreaName() string {
	if x != nil {
		return x.AreaName
	}
	return ""
}

func (x *PlayerEnterAreaResponseMessage) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PlayerEnterAreaResponseMessage) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type PlayerEnterAreaMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	X             float32                `protobuf:"fixed32,3,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,4,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerEnterAreaMessage) Reset() {
	*x = PlayerEnterAreaMessage{}
	mi := &file_shared_packets_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerEnterAreaMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerEnterAreaMessage) ProtoMessage() {}

func (x *PlayerEnterAreaMessage) ProtoReflect() protoreflect.Message {
	mi := &file_shared_packets_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerEnterAreaMessage.ProtoReflect.Descriptor instead.
func (*PlayerEnterAreaMessage) Descriptor() ([]byte, []int) {
	return file_shared_packets_proto_rawDescGZIP(), []int{7}
}

func (x *PlayerEnterAreaMessage) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *PlayerEnterAreaMessage) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PlayerEnterAreaMessage) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type PlayerLeaveAreaMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerLeaveAreaMessage) Reset() {
	*x = PlayerLeaveAreaMessage{}
	mi := &file_shared_packets_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerLeaveAreaMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerLeaveAreaMessage) ProtoMessage() {}

func (x *PlayerLeaveAreaMessage) ProtoReflect() protoreflect.Message {
	mi := &file_shared_packets_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerLeaveAreaMessage.ProtoReflect.Descriptor instead.
func (*PlayerLeaveAreaMessage) Descriptor() ([]byte, []int) {
	return file_shared_packets_proto_rawDescGZIP(), []int{8}
}

type PlayerMoveMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromX         float32                `protobuf:"fixed32,1,opt,name=from_x,json=fromX,proto3" json:"from_x,omitempty"`
	FromY         float32                `protobuf:"fixed32,2,opt,name=from_y,json=fromY,proto3" json:"from_y,omitempty"`
	ToX           float32                `protobuf:"fixed32,3,opt,name=to_x,json=toX,proto3" json:"to_x,omitempty"`
	ToY           float32                `protobuf:"fixed32,4,opt,name=to_y,json=toY,proto3" json:"to_y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerMoveMessage) Reset() {
	*x = PlayerMoveMessage{}
	mi := &file_shared_packets_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerMoveMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerMoveMessage) ProtoMessage() {}

func (x *PlayerMoveMessage) ProtoReflect() protoreflect.Message {
	mi := &file_shared_packets_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerMoveMessage.ProtoReflect.Descriptor instead.
func (*PlayerMoveMessage) Descriptor() ([]byte, []int) {
	return file_shared_packets_proto_rawDescGZIP(), []int{9}
}

func (x *PlayerMoveMessage) GetFromX() float32 {
	if x != nil {
		return x.FromX
	}
	return 0
}

func (x *PlayerMoveMessage) GetFromY() float32 {
	if x != nil {
		return x.FromY
	}
	return 0
}

func (x *PlayerMoveMessage) GetToX() float32 {
	if x != nil {
		return x.ToX
	}
	return 0
}

func (x *PlayerMoveMessage) GetToY() float32 {
	if x != nil {
		return x.ToY
	}
	return 0
}

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Type          uint32                 `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"` // 记录当前聊天内容的类型，0为当前区域，1为全局
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_shared_packets_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_shared_packets_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_shared_packets_proto_rawDescGZIP(), []int{10}
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatMessage) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ChatMessage) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

type MailRequestMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MailRequestMessage) Reset() {
	*x = MailRequestMessage{}
	mi := &file_shared_packets_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MailRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailRequestMessage) ProtoMessage() {}

func (x *MailRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_shared_packets_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailRequestMessage.ProtoReflect.Descriptor instead.
func (*MailRequestMessage) Descriptor() ([]byte, []int) {
	return file_shared_packets_proto_rawDescGZIP(), []int{11}
}

type MailMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Titles        string                 `protobuf:"bytes,2,opt,name=titles,proto3" json:"titles,omitempty"`
	Contents      string                 `protobuf:"bytes,3,opt,name=contents,proto3" json:"contents,omitempty"`
	Sender        string                 `protobuf:"bytes,4,opt,name=sender,proto3" json:"sender,omitempty"`
	Items         []*ItemMessage         `protobuf:"bytes,5,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MailMessage) Reset() {
	*x = MailMessage{}
	mi := &file_shared_packets_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MailMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailMessage) ProtoMessage() {}

func (x *MailMessage) ProtoReflect() protoreflect.Message {
	mi := &file_shared_packets_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailMessage.ProtoReflect.Descriptor instead.
func (*MailMessage) Descriptor() ([]byte, []int) {
	return file_shared_packets_proto_rawDescGZIP(), []int{12}
}

func (x *MailMessage) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MailMessage) GetTitles() string {
	if x != nil {
		return x.Titles
	}
	return ""
}

func (x *MailMessage) GetContents() string {
	if x != nil {
		return x.Contents
	}
	return ""
}

func (x *MailMessage) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *MailMessage) GetItems() []*ItemMessage {
	if x != nil {
		return x.Items
	}
	return nil
}

type MailCollectMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MailCollectMessage) Reset() {
	*x = MailCollectMessage{}
	mi := &file_shared_packets_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MailCollectMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailCollectMessage) ProtoMessage() {}

func (x *MailCollectMessage) ProtoReflect() protoreflect.Message {
	mi := &file_shared_packets_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailCollectMessage.ProtoReflect.Descriptor instead.
func (*MailCollectMessage) Descriptor() ([]byte, []int) {
	return file_shared_packets_proto_rawDescGZIP(), []int{13}
}

func (x *MailCollectMessage) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type MailCollectResponseMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Id            uint32                 `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MailCollectResponseMessage) Reset() {
	*x = MailCollectResponseMessage{}
	mi := &file_shared_packets_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MailCollectResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailCollectResponseMessage) ProtoMessage() {}

func (x *MailCollectResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_shared_packets_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailCollectResponseMessage.ProtoReflect.Descriptor instead.
func (*MailCollectResponseMessage) Descriptor() ([]byte, []int) {
	return file_shared_packets_proto_rawDescGZIP(), []int{14}
}

func (x *MailCollectResponseMessage) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MailCollectResponseMessage) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *MailCollectResponseMessage) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type MailDeleteMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MailDeleteMessage) Reset() {
	*x = MailDeleteMessage{}
	mi := &file_shared_packets_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MailDeleteMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailDeleteMessage) ProtoMessage() {}

func (x *MailDeleteMessage) ProtoReflect() protoreflect.Message {
	mi := &file_shared_packets_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailDeleteMessage.ProtoReflect.Descriptor instead.
func (*MailDeleteMessage) Descriptor() ([]byte, []int) {
	return file_shared_packets_proto_rawDescGZIP(), []int{15}
}

func (x *MailDeleteMessage) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ItemMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemMessage) Reset() {
	*x = ItemMessage{}
	mi := &file_shared_packets_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemMessage) ProtoMessage() {}

func (x *ItemMessage) ProtoReflect() protoreflect.Message {
	mi := &file_shared_packets_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemMessage.ProtoReflect.Descriptor instead.
func (*ItemMessage) Descriptor() ([]byte, []int) {
	return file_shared_packets_proto_rawDescGZIP(), []int{16}
}

func (x *ItemMessage) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ItemMessage) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type BagRequestMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BagRequestMessage) Reset() {
	*x = BagRequestMessage{}
	mi := &file_shared_packets_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BagRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BagRequestMessage) ProtoMessage() {}

func (x *BagRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_shared_packets_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BagRequestMessage.ProtoReflect.Descriptor instead.
func (*BagRequestMessage) Descriptor() ([]byte, []int) {
	return file_shared_packets_proto_rawDescGZIP(), []int{17}
}

type BagMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []uint32               `protobuf:"varint,1,rep,packed,name=id,proto3" json:"id,omitempty"`
	Count         []int64                `protobuf:"varint,2,rep,packed,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BagMessage) Reset() {
	*x = BagMessage{}
	mi := &file_shared_packets_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BagMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BagMessage) ProtoMessage() {}

func (x *BagMessage) ProtoReflect() protoreflect.Message {
	mi := &file_shared_packets_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BagMessage.ProtoReflect.Descriptor instead.
func (*BagMessage) Descriptor() ([]byte, []int) {
	return file_shared_packets_proto_rawDescGZIP(), []int{18}
}

func (x *BagMessage) GetId() []uint32 {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *BagMessage) GetCount() []int64 {
	if x != nil {
		return x.Count
	}
	return nil
}

type AddBagItemMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddBagItemMessage) Reset() {
	*x = AddBagItemMessage{}
	mi := &file_shared_packets_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddBagItemMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBagItemMessage) ProtoMessage() {}

func (x *AddBagItemMessage) ProtoReflect() protoreflect.Message {
	mi := &file_shared_packets_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBagItemMessage.ProtoReflect.Descriptor instead.
func (*AddBagItemMessage) Descriptor() ([]byte, []int) {
	return file_shared_packets_proto_rawDescGZIP(), []int{19}
}

func (x *AddBagItemMessage) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AddBagItemMessage) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type DeleteBagItemMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBagItemMessage) Reset() {
	*x = DeleteBagItemMessage{}
	mi := &file_shared_packets_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBagItemMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBagItemMessage) ProtoMessage() {}

func (x *DeleteBagItemMessage) ProtoReflect() protoreflect.Message {
	mi := &file_shared_packets_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBagItemMessage.ProtoReflect.Descriptor instead.
func (*DeleteBagItemMessage) Descriptor() ([]byte, []int) {
	return file_shared_packets_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteBagItemMessage) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeleteBagItemMessage) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type UseBagItemRequestMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UseBagItemRequestMessage) Reset() {
	*x = UseBagItemRequestMessage{}
	mi := &file_shared_packets_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UseBagItemRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseBagItemRequestMessage) ProtoMessage() {}

func (x *UseBagItemRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_shared_packets_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseBagItemRequestMessage.ProtoReflect.Descriptor instead.
func (*UseBagItemRequestMessage) Descriptor() ([]byte, []int) {
	return file_shared_packets_proto_rawDescGZIP(), []int{21}
}

func (x *UseBagItemRequestMessage) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UseBagItemRequestMessage) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type UseBagItemResponseMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UseBagItemResponseMessage) Reset() {
	*x = UseBagItemResponseMessage{}
	mi := &file_shared_packets_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UseBagItemResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseBagItemResponseMessage) ProtoMessage() {}

func (x *UseBagItemResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_shared_packets_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseBagItemResponseMessage.ProtoReflect.Descriptor instead.
func (*UseBagItemResponseMessage) Descriptor() ([]byte, []int) {
	return file_shared_packets_proto_rawDescGZIP(), []int{22}
}

func (x *UseBagItemResponseMessage) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UseBagItemResponseMessage) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type GetPetMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Equipped      bool                   `protobuf:"varint,2,opt,name=equipped,proto3" json:"equipped,omitempty"` // 是否被装备
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPetMessage) Reset() {
	*x = GetPetMessage{}
	mi := &file_shared_packets_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPetMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPetMessage) ProtoMessage() {}

func (x *GetPetMessage) ProtoReflect() protoreflect.Message {
	mi := &file_shared_packets_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPetMessage.ProtoReflect.Descriptor instead.
func (*GetPetMessage) Descriptor() ([]byte, []int) {
	return file_shared_packets_proto_rawDescGZIP(), []int{23}
}

func (x *GetPetMessage) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetPetMessage) GetEquipped() bool {
	if x != nil {
		return x.Equipped
	}
	return false
}

type PetBagRequestMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PetBagRequestMessage) Reset() {
	*x = PetBagRequestMessage{}
	mi := &file_shared_packets_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetBagRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetBagRequestMessage) ProtoMessage() {}

func (x *PetBagRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_shared_packets_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetBagRequestMessage.ProtoReflect.Descriptor instead.
func (*PetBagRequestMessage) Descriptor() ([]byte, []int) {
	return file_shared_packets_proto_rawDescGZIP(), []int{24}
}

type PetBagResponseMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pet           []*PetMessage          `protobuf:"bytes,1,rep,name=pet,proto3" json:"pet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PetBagResponseMessage) Reset() {
	*x = PetBagResponseMessage{}
	mi := &file_shared_packets_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetBagResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetBagResponseMessage) ProtoMessage() {}

func (x *PetBagResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_shared_packets_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetBagResponseMessage.ProtoReflect.Descriptor instead.
func (*PetBagResponseMessage) Descriptor() ([]byte, []int) {
	return file_shared_packets_proto_rawDescGZIP(), []int{25}
}

func (x *PetBagResponseMessage) GetPet() []*PetMessage {
	if x != nil {
		return x.Pet
	}
	return nil
}

type PetMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PetId          uint32                 `protobuf:"varint,1,opt,name=pet_id,json=petId,proto3" json:"pet_id,omitempty"`
	Id             uint64                 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Exp            int64                  `protobuf:"varint,3,opt,name=exp,proto3" json:"exp,omitempty"`
	Level          int64                  `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	EquippedSkills []uint32               `protobuf:"varint,5,rep,packed,name=equipped_skills,json=equippedSkills,proto3" json:"equipped_skills,omitempty"`
	PetStats       *PetStatsMessage       `protobuf:"bytes,6,opt,name=pet_stats,json=petStats,proto3" json:"pet_stats,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PetMessage) Reset() {
	*x = PetMessage{}
	mi := &file_shared_packets_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetMessage) ProtoMessage() {}

func (x *PetMessage) ProtoReflect() protoreflect.Message {
	mi := &file_shared_packets_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetMessage.ProtoReflect.Descriptor instead.
func (*PetMessage) Descriptor() ([]byte, []int) {
	return file_shared_packets_proto_rawDescGZIP(), []int{26}
}

func (x *PetMessage) GetPetId() uint32 {
	if x != nil {
		return x.PetId
	}
	return 0
}

func (x *PetMessage) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PetMessage) GetExp() int64 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *PetMessage) GetLevel() int64 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *PetMessage) GetEquippedSkills() []uint32 {
	if x != nil {
		return x.EquippedSkills
	}
	return nil
}

func (x *PetMessage) GetPetStats() *PetStatsMessage {
	if x != nil {
		return x.PetStats
	}
	return nil
}

type PetStatsMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaxHp         int64                  `protobuf:"varint,1,opt,name=max_hp,json=maxHp,proto3" json:"max_hp,omitempty"`
	Hp            int64                  `protobuf:"varint,2,opt,name=hp,proto3" json:"hp,omitempty"`
	MaxMana       int64                  `protobuf:"varint,3,opt,name=max_mana,json=maxMana,proto3" json:"max_mana,omitempty"`
	Mana          int64                  `protobuf:"varint,4,opt,name=mana,proto3" json:"mana,omitempty"`
	Strength      int64                  `protobuf:"varint,5,opt,name=strength,proto3" json:"strength,omitempty"`
	Intelligence  int64                  `protobuf:"varint,6,opt,name=intelligence,proto3" json:"intelligence,omitempty"`
	Speed         int64                  `protobuf:"varint,7,opt,name=speed,proto3" json:"speed,omitempty"`
	Defense       int64                  `protobuf:"varint,8,opt,name=defense,proto3" json:"defense,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PetStatsMessage) Reset() {
	*x = PetStatsMessage{}
	mi := &file_shared_packets_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetStatsMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetStatsMessage) ProtoMessage() {}

func (x *PetStatsMessage) ProtoReflect() protoreflect.Message {
	mi := &file_shared_packets_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetStatsMessage.ProtoReflect.Descriptor instead.
func (*PetStatsMessage) Descriptor() ([]byte, []int) {
	return file_shared_packets_proto_rawDescGZIP(), []int{27}
}

func (x *PetStatsMessage) GetMaxHp() int64 {
	if x != nil {
		return x.MaxHp
	}
	return 0
}

func (x *PetStatsMessage) GetHp() int64 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *PetStatsMessage) GetMaxMana() int64 {
	if x != nil {
		return x.MaxMana
	}
	return 0
}

func (x *PetStatsMessage) GetMana() int64 {
	if x != nil {
		return x.Mana
	}
	return 0
}

func (x *PetStatsMessage) GetStrength() int64 {
	if x != nil {
		return x.Strength
	}
	return 0
}

func (x *PetStatsMessage) GetIntelligence() int64 {
	if x != nil {
		return x.Intelligence
	}
	return 0
}

func (x *PetStatsMessage) GetSpeed() int64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *PetStatsMessage) GetDefense() int64 {
	if x != nil {
		return x.Defense
	}
	return 0
}

type SavePetMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SavePetMessage) Reset() {
	*x = SavePetMessage{}
	mi := &file_shared_packets_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SavePetMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SavePetMessage) ProtoMessage() {}

func (x *SavePetMessage) ProtoReflect() protoreflect.Message {
	mi := &file_shared_packets_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SavePetMessage.ProtoReflect.Descriptor instead.
func (*SavePetMessage) Descriptor() ([]byte, []int) {
	return file_shared_packets_proto_rawDescGZIP(), []int{28}
}

type Packet struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Uid   uint32                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	// Types that are valid to be assigned to Msg:
	//
	//	*Packet_LoginRequest
	//	*Packet_RegisterRequest
	//	*Packet_OkResponse
	//	*Packet_DenyResponse
	//	*Packet_LoginSuccess
	//	*Packet_PlayerEnter
	//	*Packet_PlayerLeave
	//	*Packet_PlayerMovement
	//	*Packet_PlayerEnterRequest
	//	*Packet_Chat
	//	*Packet_PlayerEnterAreaResponse
	//	*Packet_Mail
	//	*Packet_MailRequest
	//	*Packet_MailCollect
	//	*Packet_MailDelete
	//	*Packet_MailCollectResponse
	//	*Packet_BagRequest
	//	*Packet_Bag
	//	*Packet_AddBagItem
	//	*Packet_DeleteBagItem
	//	*Packet_UseBagItemRequest
	//	*Packet_UseBagItemResponse
	//	*Packet_UiPacket
	//	*Packet_GetPet
	//	*Packet_PetBagRequest
	//	*Packet_PetBagResponse
	//	*Packet_SavePet
	Msg           isPacket_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Packet) Reset() {
	*x = Packet{}
	mi := &file_shared_packets_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_shared_packets_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_shared_packets_proto_rawDescGZIP(), []int{29}
}

func (x *Packet) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Packet) GetMsg() isPacket_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *Packet) GetLoginRequest() *LoginRequestMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_LoginRequest); ok {
			return x.LoginRequest
		}
	}
	return nil
}

func (x *Packet) GetRegisterRequest() *RegisterRequestMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_RegisterRequest); ok {
			return x.RegisterRequest
		}
	}
	return nil
}

func (x *Packet) GetOkResponse() *OKResponseMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_OkResponse); ok {
			return x.OkResponse
		}
	}
	return nil
}

func (x *Packet) GetDenyResponse() *DenyResponseMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_DenyResponse); ok {
			return x.DenyResponse
		}
	}
	return nil
}

func (x *Packet) GetLoginSuccess() *LoginSuccessMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_LoginSuccess); ok {
			return x.LoginSuccess
		}
	}
	return nil
}

func (x *Packet) GetPlayerEnter() *PlayerEnterAreaMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_PlayerEnter); ok {
			return x.PlayerEnter
		}
	}
	return nil
}

func (x *Packet) GetPlayerLeave() *PlayerLeaveAreaMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_PlayerLeave); ok {
			return x.PlayerLeave
		}
	}
	return nil
}

func (x *Packet) GetPlayerMovement() *PlayerMoveMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_PlayerMovement); ok {
			return x.PlayerMovement
		}
	}
	return nil
}

func (x *Packet) GetPlayerEnterRequest() *PlayerEnterAreaRequestMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_PlayerEnterRequest); ok {
			return x.PlayerEnterRequest
		}
	}
	return nil
}

func (x *Packet) GetChat() *ChatMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_Chat); ok {
			return x.Chat
		}
	}
	return nil
}

func (x *Packet) GetPlayerEnterAreaResponse() *PlayerEnterAreaResponseMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_PlayerEnterAreaResponse); ok {
			return x.PlayerEnterAreaResponse
		}
	}
	return nil
}

func (x *Packet) GetMail() *MailMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_Mail); ok {
			return x.Mail
		}
	}
	return nil
}

func (x *Packet) GetMailRequest() *MailRequestMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_MailRequest); ok {
			return x.MailRequest
		}
	}
	return nil
}

func (x *Packet) GetMailCollect() *MailCollectMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_MailCollect); ok {
			return x.MailCollect
		}
	}
	return nil
}

func (x *Packet) GetMailDelete() *MailDeleteMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_MailDelete); ok {
			return x.MailDelete
		}
	}
	return nil
}

func (x *Packet) GetMailCollectResponse() *MailCollectResponseMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_MailCollectResponse); ok {
			return x.MailCollectResponse
		}
	}
	return nil
}

func (x *Packet) GetBagRequest() *BagRequestMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_BagRequest); ok {
			return x.BagRequest
		}
	}
	return nil
}

func (x *Packet) GetBag() *BagMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_Bag); ok {
			return x.Bag
		}
	}
	return nil
}

func (x *Packet) GetAddBagItem() *AddBagItemMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_AddBagItem); ok {
			return x.AddBagItem
		}
	}
	return nil
}

func (x *Packet) GetDeleteBagItem() *DeleteBagItemMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_DeleteBagItem); ok {
			return x.DeleteBagItem
		}
	}
	return nil
}

func (x *Packet) GetUseBagItemRequest() *UseBagItemRequestMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_UseBagItemRequest); ok {
			return x.UseBagItemRequest
		}
	}
	return nil
}

func (x *Packet) GetUseBagItemResponse() *UseBagItemResponseMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_UseBagItemResponse); ok {
			return x.UseBagItemResponse
		}
	}
	return nil
}

func (x *Packet) GetUiPacket() *UiPacket {
	if x != nil {
		if x, ok := x.Msg.(*Packet_UiPacket); ok {
			return x.UiPacket
		}
	}
	return nil
}

func (x *Packet) GetGetPet() *GetPetMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_GetPet); ok {
			return x.GetPet
		}
	}
	return nil
}

func (x *Packet) GetPetBagRequest() *PetBagRequestMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_PetBagRequest); ok {
			return x.PetBagRequest
		}
	}
	return nil
}

func (x *Packet) GetPetBagResponse() *PetBagResponseMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_PetBagResponse); ok {
			return x.PetBagResponse
		}
	}
	return nil
}

func (x *Packet) GetSavePet() *SavePetMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_SavePet); ok {
			return x.SavePet
		}
	}
	return nil
}

type isPacket_Msg interface {
	isPacket_Msg()
}

type Packet_LoginRequest struct {
	LoginRequest *LoginRequestMessage `protobuf:"bytes,2,opt,name=login_request,json=loginRequest,proto3,oneof"`
}

type Packet_RegisterRequest struct {
	RegisterRequest *RegisterRequestMessage `protobuf:"bytes,3,opt,name=register_request,json=registerRequest,proto3,oneof"`
}

type Packet_OkResponse struct {
	OkResponse *OKResponseMessage `protobuf:"bytes,4,opt,name=ok_response,json=okResponse,proto3,oneof"`
}

type Packet_DenyResponse struct {
	DenyResponse *DenyResponseMessage `protobuf:"bytes,5,opt,name=deny_response,json=denyResponse,proto3,oneof"`
}

type Packet_LoginSuccess struct {
	LoginSuccess *LoginSuccessMessage `protobuf:"bytes,6,opt,name=login_success,json=loginSuccess,proto3,oneof"`
}

type Packet_PlayerEnter struct {
	PlayerEnter *PlayerEnterAreaMessage `protobuf:"bytes,7,opt,name=player_enter,json=playerEnter,proto3,oneof"`
}

type Packet_PlayerLeave struct {
	PlayerLeave *PlayerLeaveAreaMessage `protobuf:"bytes,8,opt,name=player_leave,json=playerLeave,proto3,oneof"`
}

type Packet_PlayerMovement struct {
	PlayerMovement *PlayerMoveMessage `protobuf:"bytes,9,opt,name=player_movement,json=playerMovement,proto3,oneof"`
}

type Packet_PlayerEnterRequest struct {
	PlayerEnterRequest *PlayerEnterAreaRequestMessage `protobuf:"bytes,10,opt,name=player_enter_request,json=playerEnterRequest,proto3,oneof"`
}

type Packet_Chat struct {
	Chat *ChatMessage `protobuf:"bytes,11,opt,name=chat,proto3,oneof"`
}

type Packet_PlayerEnterAreaResponse struct {
	PlayerEnterAreaResponse *PlayerEnterAreaResponseMessage `protobuf:"bytes,12,opt,name=player_enter_area_response,json=playerEnterAreaResponse,proto3,oneof"`
}

type Packet_Mail struct {
	Mail *MailMessage `protobuf:"bytes,13,opt,name=mail,proto3,oneof"`
}

type Packet_MailRequest struct {
	MailRequest *MailRequestMessage `protobuf:"bytes,14,opt,name=mail_request,json=mailRequest,proto3,oneof"`
}

type Packet_MailCollect struct {
	MailCollect *MailCollectMessage `protobuf:"bytes,15,opt,name=mail_collect,json=mailCollect,proto3,oneof"`
}

type Packet_MailDelete struct {
	MailDelete *MailDeleteMessage `protobuf:"bytes,16,opt,name=mail_delete,json=mailDelete,proto3,oneof"`
}

type Packet_MailCollectResponse struct {
	MailCollectResponse *MailCollectResponseMessage `protobuf:"bytes,17,opt,name=mail_collect_response,json=mailCollectResponse,proto3,oneof"`
}

type Packet_BagRequest struct {
	BagRequest *BagRequestMessage `protobuf:"bytes,18,opt,name=bag_request,json=bagRequest,proto3,oneof"`
}

type Packet_Bag struct {
	Bag *BagMessage `protobuf:"bytes,19,opt,name=bag,proto3,oneof"`
}

type Packet_AddBagItem struct {
	AddBagItem *AddBagItemMessage `protobuf:"bytes,20,opt,name=add_bag_item,json=addBagItem,proto3,oneof"`
}

type Packet_DeleteBagItem struct {
	DeleteBagItem *DeleteBagItemMessage `protobuf:"bytes,21,opt,name=delete_bag_item,json=deleteBagItem,proto3,oneof"`
}

type Packet_UseBagItemRequest struct {
	UseBagItemRequest *UseBagItemRequestMessage `protobuf:"bytes,22,opt,name=use_bag_item_request,json=useBagItemRequest,proto3,oneof"`
}

type Packet_UseBagItemResponse struct {
	UseBagItemResponse *UseBagItemResponseMessage `protobuf:"bytes,23,opt,name=use_bag_item_response,json=useBagItemResponse,proto3,oneof"`
}

type Packet_UiPacket struct {
	UiPacket *UiPacket `protobuf:"bytes,24,opt,name=ui_packet,json=uiPacket,proto3,oneof"`
}

type Packet_GetPet struct {
	GetPet *GetPetMessage `protobuf:"bytes,25,opt,name=get_pet,json=getPet,proto3,oneof"`
}

type Packet_PetBagRequest struct {
	PetBagRequest *PetBagRequestMessage `protobuf:"bytes,26,opt,name=pet_bag_request,json=petBagRequest,proto3,oneof"`
}

type Packet_PetBagResponse struct {
	PetBagResponse *PetBagResponseMessage `protobuf:"bytes,27,opt,name=pet_bag_response,json=petBagResponse,proto3,oneof"`
}

type Packet_SavePet struct {
	SavePet *SavePetMessage `protobuf:"bytes,28,opt,name=save_pet,json=savePet,proto3,oneof"`
}

func (*Packet_LoginRequest) isPacket_Msg() {}

func (*Packet_RegisterRequest) isPacket_Msg() {}

func (*Packet_OkResponse) isPacket_Msg() {}

func (*Packet_DenyResponse) isPacket_Msg() {}

func (*Packet_LoginSuccess) isPacket_Msg() {}

func (*Packet_PlayerEnter) isPacket_Msg() {}

func (*Packet_PlayerLeave) isPacket_Msg() {}

func (*Packet_PlayerMovement) isPacket_Msg() {}

func (*Packet_PlayerEnterRequest) isPacket_Msg() {}

func (*Packet_Chat) isPacket_Msg() {}

func (*Packet_PlayerEnterAreaResponse) isPacket_Msg() {}

func (*Packet_Mail) isPacket_Msg() {}

func (*Packet_MailRequest) isPacket_Msg() {}

func (*Packet_MailCollect) isPacket_Msg() {}

func (*Packet_MailDelete) isPacket_Msg() {}

func (*Packet_MailCollectResponse) isPacket_Msg() {}

func (*Packet_BagRequest) isPacket_Msg() {}

func (*Packet_Bag) isPacket_Msg() {}

func (*Packet_AddBagItem) isPacket_Msg() {}

func (*Packet_DeleteBagItem) isPacket_Msg() {}

func (*Packet_UseBagItemRequest) isPacket_Msg() {}

func (*Packet_UseBagItemResponse) isPacket_Msg() {}

func (*Packet_UiPacket) isPacket_Msg() {}

func (*Packet_GetPet) isPacket_Msg() {}

func (*Packet_PetBagRequest) isPacket_Msg() {}

func (*Packet_PetBagResponse) isPacket_Msg() {}

func (*Packet_SavePet) isPacket_Msg() {}

type UiPacket struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*UiPacket_OpenUi
	//	*UiPacket_InitialPetRequest
	Msg           isUiPacket_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UiPacket) Reset() {
	*x = UiPacket{}
	mi := &file_shared_packets_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UiPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UiPacket) ProtoMessage() {}

func (x *UiPacket) ProtoReflect() protoreflect.Message {
	mi := &file_shared_packets_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UiPacket.ProtoReflect.Descriptor instead.
func (*UiPacket) Descriptor() ([]byte, []int) {
	return file_shared_packets_proto_rawDescGZIP(), []int{30}
}

func (x *UiPacket) GetMsg() isUiPacket_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *UiPacket) GetOpenUi() *OpenUIMessage {
	if x != nil {
		if x, ok := x.Msg.(*UiPacket_OpenUi); ok {
			return x.OpenUi
		}
	}
	return nil
}

func (x *UiPacket) GetInitialPetRequest() *InitialPetRequestMessage {
	if x != nil {
		if x, ok := x.Msg.(*UiPacket_InitialPetRequest); ok {
			return x.InitialPetRequest
		}
	}
	return nil
}

type isUiPacket_Msg interface {
	isUiPacket_Msg()
}

type UiPacket_OpenUi struct {
	OpenUi *OpenUIMessage `protobuf:"bytes,1,opt,name=open_ui,json=openUi,proto3,oneof"`
}

type UiPacket_InitialPetRequest struct {
	InitialPetRequest *InitialPetRequestMessage `protobuf:"bytes,2,opt,name=initial_pet_request,json=initialPetRequest,proto3,oneof"`
}

func (*UiPacket_OpenUi) isUiPacket_Msg() {}

func (*UiPacket_InitialPetRequest) isUiPacket_Msg() {}

type OpenUIMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenUIMessage) Reset() {
	*x = OpenUIMessage{}
	mi := &file_shared_packets_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenUIMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenUIMessage) ProtoMessage() {}

func (x *OpenUIMessage) ProtoReflect() protoreflect.Message {
	mi := &file_shared_packets_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenUIMessage.ProtoReflect.Descriptor instead.
func (*OpenUIMessage) Descriptor() ([]byte, []int) {
	return file_shared_packets_proto_rawDescGZIP(), []int{31}
}

func (x *OpenUIMessage) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type InitialPetRequestMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint32                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitialPetRequestMessage) Reset() {
	*x = InitialPetRequestMessage{}
	mi := &file_shared_packets_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitialPetRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitialPetRequestMessage) ProtoMessage() {}

func (x *InitialPetRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_shared_packets_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitialPetRequestMessage.ProtoReflect.Descriptor instead.
func (*InitialPetRequestMessage) Descriptor() ([]byte, []int) {
	return file_shared_packets_proto_rawDescGZIP(), []int{32}
}

func (x *InitialPetRequestMessage) GetRequestId() uint32 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

var File_shared_packets_proto protoreflect.FileDescriptor

const file_shared_packets_proto_rawDesc = "" +
	"\n" +
	"\x14shared/packets.proto\x12\apackets\"M\n" +
	"\x13LoginRequestMessage\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"P\n" +
	"\x16RegisterRequestMessage\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x13\n" +
	"\x11OKResponseMessage\"-\n" +
	"\x13DenyResponseMessage\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"C\n" +
	"\x13LoginSuccessMessage\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\rR\x03uid\"]\n" +
	"\x1dPlayerEnterAreaRequestMessage\x12\x1b\n" +
	"\tarea_name\x18\x01 \x01(\tR\bareaName\x12\x1f\n" +
	"\ventrance_id\x18\x02 \x01(\rR\n" +
	"entranceId\"o\n" +
	"\x1ePlayerEnterAreaResponseMessage\x12\x1b\n" +
	"\tarea_name\x18\x01 \x01(\tR\bareaName\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"P\n" +
	"\x16PlayerEnterAreaMessage\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\f\n" +
	"\x01x\x18\x03 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x04 \x01(\x02R\x01y\"\x18\n" +
	"\x16PlayerLeaveAreaMessage\"g\n" +
	"\x11PlayerMoveMessage\x12\x15\n" +
	"\x06from_x\x18\x01 \x01(\x02R\x05fromX\x12\x15\n" +
	"\x06from_y\x18\x02 \x01(\x02R\x05fromY\x12\x11\n" +
	"\x04to_x\x18\x03 \x01(\x02R\x03toX\x12\x11\n" +
	"\x04to_y\x18\x04 \x01(\x02R\x03toY\"W\n" +
	"\vChatMessage\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x12\n" +
	"\x04type\x18\x03 \x01(\rR\x04type\"\x14\n" +
	"\x12MailRequestMessage\"\x95\x01\n" +
	"\vMailMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x16\n" +
	"\x06titles\x18\x02 \x01(\tR\x06titles\x12\x1a\n" +
	"\bcontents\x18\x03 \x01(\tR\bcontents\x12\x16\n" +
	"\x06sender\x18\x04 \x01(\tR\x06sender\x12*\n" +
	"\x05items\x18\x05 \x03(\v2\x14.packets.ItemMessageR\x05items\"$\n" +
	"\x12MailCollectMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"^\n" +
	"\x1aMailCollectResponseMessage\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\rR\x02id\"#\n" +
	"\x11MailDeleteMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"3\n" +
	"\vItemMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\"\x13\n" +
	"\x11BagRequestMessage\"2\n" +
	"\n" +
	"BagMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x03(\rR\x02id\x12\x14\n" +
	"\x05count\x18\x02 \x03(\x03R\x05count\"9\n" +
	"\x11AddBagItemMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\"<\n" +
	"\x14DeleteBagItemMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\"@\n" +
	"\x18UseBagItemRequestMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\"M\n" +
	"\x19UseBagItemResponseMessage\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\";\n" +
	"\rGetPetMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1a\n" +
	"\bequipped\x18\x02 \x01(\bR\bequipped\"\x16\n" +
	"\x14PetBagRequestMessage\">\n" +
	"\x15PetBagResponseMessage\x12%\n" +
	"\x03pet\x18\x01 \x03(\v2\x13.packets.PetMessageR\x03pet\"\xbb\x01\n" +
	"\n" +
	"PetMessage\x12\x15\n" +
	"\x06pet_id\x18\x01 \x01(\rR\x05petId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x04R\x02id\x12\x10\n" +
	"\x03exp\x18\x03 \x01(\x03R\x03exp\x12\x14\n" +
	"\x05level\x18\x04 \x01(\x03R\x05level\x12'\n" +
	"\x0fequipped_skills\x18\x05 \x03(\rR\x0eequippedSkills\x125\n" +
	"\tpet_stats\x18\x06 \x01(\v2\x18.packets.PetStatsMessageR\bpetStats\"\xd7\x01\n" +
	"\x0fPetStatsMessage\x12\x15\n" +
	"\x06max_hp\x18\x01 \x01(\x03R\x05maxHp\x12\x0e\n" +
	"\x02hp\x18\x02 \x01(\x03R\x02hp\x12\x19\n" +
	"\bmax_mana\x18\x03 \x01(\x03R\amaxMana\x12\x12\n" +
	"\x04mana\x18\x04 \x01(\x03R\x04mana\x12\x1a\n" +
	"\bstrength\x18\x05 \x01(\x03R\bstrength\x12\"\n" +
	"\fintelligence\x18\x06 \x01(\x03R\fintelligence\x12\x14\n" +
	"\x05speed\x18\a \x01(\x03R\x05speed\x12\x18\n" +
	"\adefense\x18\b \x01(\x03R\adefense\"\x10\n" +
	"\x0eSavePetMessage\"\xda\x0e\n" +
	"\x06Packet\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\rR\x03uid\x12C\n" +
	"\rlogin_request\x18\x02 \x01(\v2\x1c.packets.LoginRequestMessageH\x00R\floginRequest\x12L\n" +
	"\x10register_request\x18\x03 \x01(\v2\x1f.packets.RegisterRequestMessageH\x00R\x0fregisterRequest\x12=\n" +
	"\vok_response\x18\x04 \x01(\v2\x1a.packets.OKResponseMessageH\x00R\n" +
	"okResponse\x12C\n" +
	"\rdeny_response\x18\x05 \x01(\v2\x1c.packets.DenyResponseMessageH\x00R\fdenyResponse\x12C\n" +
	"\rlogin_success\x18\x06 \x01(\v2\x1c.packets.LoginSuccessMessageH\x00R\floginSuccess\x12D\n" +
	"\fplayer_enter\x18\a \x01(\v2\x1f.packets.PlayerEnterAreaMessageH\x00R\vplayerEnter\x12D\n" +
	"\fplayer_leave\x18\b \x01(\v2\x1f.packets.PlayerLeaveAreaMessageH\x00R\vplayerLeave\x12E\n" +
	"\x0fplayer_movement\x18\t \x01(\v2\x1a.packets.PlayerMoveMessageH\x00R\x0eplayerMovement\x12Z\n" +
	"\x14player_enter_request\x18\n" +
	" \x01(\v2&.packets.PlayerEnterAreaRequestMessageH\x00R\x12playerEnterRequest\x12*\n" +
	"\x04chat\x18\v \x01(\v2\x14.packets.ChatMessageH\x00R\x04chat\x12f\n" +
	"\x1aplayer_enter_area_response\x18\f \x01(\v2'.packets.PlayerEnterAreaResponseMessageH\x00R\x17playerEnterAreaResponse\x12*\n" +
	"\x04mail\x18\r \x01(\v2\x14.packets.MailMessageH\x00R\x04mail\x12@\n" +
	"\fmail_request\x18\x0e \x01(\v2\x1b.packets.MailRequestMessageH\x00R\vmailRequest\x12@\n" +
	"\fmail_collect\x18\x0f \x01(\v2\x1b.packets.MailCollectMessageH\x00R\vmailCollect\x12=\n" +
	"\vmail_delete\x18\x10 \x01(\v2\x1a.packets.MailDeleteMessageH\x00R\n" +
	"mailDelete\x12Y\n" +
	"\x15mail_collect_response\x18\x11 \x01(\v2#.packets.MailCollectResponseMessageH\x00R\x13mailCollectResponse\x12=\n" +
	"\vbag_request\x18\x12 \x01(\v2\x1a.packets.BagRequestMessageH\x00R\n" +
	"bagRequest\x12'\n" +
	"\x03bag\x18\x13 \x01(\v2\x13.packets.BagMessageH\x00R\x03bag\x12>\n" +
	"\fadd_bag_item\x18\x14 \x01(\v2\x1a.packets.AddBagItemMessageH\x00R\n" +
	"addBagItem\x12G\n" +
	"\x0fdelete_bag_item\x18\x15 \x01(\v2\x1d.packets.DeleteBagItemMessageH\x00R\rdeleteBagItem\x12T\n" +
	"\x14use_bag_item_request\x18\x16 \x01(\v2!.packets.UseBagItemRequestMessageH\x00R\x11useBagItemRequest\x12W\n" +
	"\x15use_bag_item_response\x18\x17 \x01(\v2\".packets.UseBagItemResponseMessageH\x00R\x12useBagItemResponse\x120\n" +
	"\tui_packet\x18\x18 \x01(\v2\x11.packets.UiPacketH\x00R\buiPacket\x121\n" +
	"\aget_pet\x18\x19 \x01(\v2\x16.packets.GetPetMessageH\x00R\x06getPet\x12G\n" +
	"\x0fpet_bag_request\x18\x1a \x01(\v2\x1d.packets.PetBagRequestMessageH\x00R\rpetBagRequest\x12J\n" +
	"\x10pet_bag_response\x18\x1b \x01(\v2\x1e.packets.PetBagResponseMessageH\x00R\x0epetBagResponse\x124\n" +
	"\bsave_pet\x18\x1c \x01(\v2\x17.packets.SavePetMessageH\x00R\asavePetB\x05\n" +
	"\x03msg\"\x99\x01\n" +
	"\bUiPacket\x121\n" +
	"\aopen_ui\x18\x01 \x01(\v2\x16.packets.OpenUIMessageH\x00R\x06openUi\x12S\n" +
	"\x13initial_pet_request\x18\x02 \x01(\v2!.packets.InitialPetRequestMessageH\x00R\x11initialPetRequestB\x05\n" +
	"\x03msg\"#\n" +
	"\rOpenUIMessage\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"9\n" +
	"\x18InitialPetRequestMessage\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\rR\trequestIdB\rZ\vpkg/packetsb\x06proto3"

var (
	file_shared_packets_proto_rawDescOnce sync.Once
	file_shared_packets_proto_rawDescData []byte
)

func file_shared_packets_proto_rawDescGZIP() []byte {
	file_shared_packets_proto_rawDescOnce.Do(func() {
		file_shared_packets_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_packets_proto_rawDesc), len(file_shared_packets_proto_rawDesc)))
	})
	return file_shared_packets_proto_rawDescData
}

var file_shared_packets_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_shared_packets_proto_goTypes = []any{
	(*LoginRequestMessage)(nil),            // 0: packets.LoginRequestMessage
	(*RegisterRequestMessage)(nil),         // 1: packets.RegisterRequestMessage
	(*OKResponseMessage)(nil),              // 2: packets.OKResponseMessage
	(*DenyResponseMessage)(nil),            // 3: packets.DenyResponseMessage
	(*LoginSuccessMessage)(nil),            // 4: packets.LoginSuccessMessage
	(*PlayerEnterAreaRequestMessage)(nil),  // 5: packets.PlayerEnterAreaRequestMessage
	(*PlayerEnterAreaResponseMessage)(nil), // 6: packets.PlayerEnterAreaResponseMessage
	(*PlayerEnterAreaMessage)(nil),         // 7: packets.PlayerEnterAreaMessage
	(*PlayerLeaveAreaMessage)(nil),         // 8: packets.PlayerLeaveAreaMessage
	(*PlayerMoveMessage)(nil),              // 9: packets.PlayerMoveMessage
	(*ChatMessage)(nil),                    // 10: packets.ChatMessage
	(*MailRequestMessage)(nil),             // 11: packets.MailRequestMessage
	(*MailMessage)(nil),                    // 12: packets.MailMessage
	(*MailCollectMessage)(nil),             // 13: packets.MailCollectMessage
	(*MailCollectResponseMessage)(nil),     // 14: packets.MailCollectResponseMessage
	(*MailDeleteMessage)(nil),              // 15: packets.MailDeleteMessage
	(*ItemMessage)(nil),                    // 16: packets.ItemMessage
	(*BagRequestMessage)(nil),              // 17: packets.BagRequestMessage
	(*BagMessage)(nil),                     // 18: packets.BagMessage
	(*AddBagItemMessage)(nil),              // 19: packets.AddBagItemMessage
	(*DeleteBagItemMessage)(nil),           // 20: packets.DeleteBagItemMessage
	(*UseBagItemRequestMessage)(nil),       // 21: packets.UseBagItemRequestMessage
	(*UseBagItemResponseMessage)(nil),      // 22: packets.UseBagItemResponseMessage
	(*GetPetMessage)(nil),                  // 23: packets.GetPetMessage
	(*PetBagRequestMessage)(nil),           // 24: packets.PetBagRequestMessage
	(*PetBagResponseMessage)(nil),          // 25: packets.PetBagResponseMessage
	(*PetMessage)(nil),                     // 26: packets.PetMessage
	(*PetStatsMessage)(nil),                // 27: packets.PetStatsMessage
	(*SavePetMessage)(nil),                 // 28: packets.SavePetMessage
	(*Packet)(nil),                         // 29: packets.Packet
	(*UiPacket)(nil),                       // 30: packets.UiPacket
	(*OpenUIMessage)(nil),                  // 31: packets.OpenUIMessage
	(*InitialPetRequestMessage)(nil),       // 32: packets.InitialPetRequestMessage
}
var file_shared_packets_proto_depIdxs = []int32{
	16, // 0: packets.MailMessage.items:type_name -> packets.ItemMessage
	26, // 1: packets.PetBagResponseMessage.pet:type_name -> packets.PetMessage
	27, // 2: packets.PetMessage.pet_stats:type_name -> packets.PetStatsMessage
	0,  // 3: packets.Packet.login_request:type_name -> packets.LoginRequestMessage
	1,  // 4: packets.Packet.register_request:type_name -> packets.RegisterRequestMessage
	2,  // 5: packets.Packet.ok_response:type_name -> packets.OKResponseMessage
	3,  // 6: packets.Packet.deny_response:type_name -> packets.DenyResponseMessage
	4,  // 7: packets.Packet.login_success:type_name -> packets.LoginSuccessMessage
	7,  // 8: packets.Packet.player_enter:type_name -> packets.PlayerEnterAreaMessage
	8,  // 9: packets.Packet.player_leave:type_name -> packets.PlayerLeaveAreaMessage
	9,  // 10: packets.Packet.player_movement:type_name -> packets.PlayerMoveMessage
	5,  // 11: packets.Packet.player_enter_request:type_name -> packets.PlayerEnterAreaRequestMessage
	10, // 12: packets.Packet.chat:type_name -> packets.ChatMessage
	6,  // 13: packets.Packet.player_enter_area_response:type_name -> packets.PlayerEnterAreaResponseMessage
	12, // 14: packets.Packet.mail:type_name -> packets.MailMessage
	11, // 15: packets.Packet.mail_request:type_name -> packets.MailRequestMessage
	13, // 16: packets.Packet.mail_collect:type_name -> packets.MailCollectMessage
	15, // 17: packets.Packet.mail_delete:type_name -> packets.MailDeleteMessage
	14, // 18: packets.Packet.mail_collect_response:type_name -> packets.MailCollectResponseMessage
	17, // 19: packets.Packet.bag_request:type_name -> packets.BagRequestMessage
	18, // 20: packets.Packet.bag:type_name -> packets.BagMessage
	19, // 21: packets.Packet.add_bag_item:type_name -> packets.AddBagItemMessage
	20, // 22: packets.Packet.delete_bag_item:type_name -> packets.DeleteBagItemMessage
	21, // 23: packets.Packet.use_bag_item_request:type_name -> packets.UseBagItemRequestMessage
	22, // 24: packets.Packet.use_bag_item_response:type_name -> packets.UseBagItemResponseMessage
	30, // 25: packets.Packet.ui_packet:type_name -> packets.UiPacket
	23, // 26: packets.Packet.get_pet:type_name -> packets.GetPetMessage
	24, // 27: packets.Packet.pet_bag_request:type_name -> packets.PetBagRequestMessage
	25, // 28: packets.Packet.pet_bag_response:type_name -> packets.PetBagResponseMessage
	28, // 29: packets.Packet.save_pet:type_name -> packets.SavePetMessage
	31, // 30: packets.UiPacket.open_ui:type_name -> packets.OpenUIMessage
	32, // 31: packets.UiPacket.initial_pet_request:type_name -> packets.InitialPetRequestMessage
	32, // [32:32] is the sub-list for method output_type
	32, // [32:32] is the sub-list for method input_type
	32, // [32:32] is the sub-list for extension type_name
	32, // [32:32] is the sub-list for extension extendee
	0,  // [0:32] is the sub-list for field type_name
}

func init() { file_shared_packets_proto_init() }
func file_shared_packets_proto_init() {
	if File_shared_packets_proto != nil {
		return
	}
	file_shared_packets_proto_msgTypes[29].OneofWrappers = []any{
		(*Packet_LoginRequest)(nil),
		(*Packet_RegisterRequest)(nil),
		(*Packet_OkResponse)(nil),
		(*Packet_DenyResponse)(nil),
		(*Packet_LoginSuccess)(nil),
		(*Packet_PlayerEnter)(nil),
		(*Packet_PlayerLeave)(nil),
		(*Packet_PlayerMovement)(nil),
		(*Packet_PlayerEnterRequest)(nil),
		(*Packet_Chat)(nil),
		(*Packet_PlayerEnterAreaResponse)(nil),
		(*Packet_Mail)(nil),
		(*Packet_MailRequest)(nil),
		(*Packet_MailCollect)(nil),
		(*Packet_MailDelete)(nil),
		(*Packet_MailCollectResponse)(nil),
		(*Packet_BagRequest)(nil),
		(*Packet_Bag)(nil),
		(*Packet_AddBagItem)(nil),
		(*Packet_DeleteBagItem)(nil),
		(*Packet_UseBagItemRequest)(nil),
		(*Packet_UseBagItemResponse)(nil),
		(*Packet_UiPacket)(nil),
		(*Packet_GetPet)(nil),
		(*Packet_PetBagRequest)(nil),
		(*Packet_PetBagResponse)(nil),
		(*Packet_SavePet)(nil),
	}
	file_shared_packets_proto_msgTypes[30].OneofWrappers = []any{
		(*UiPacket_OpenUi)(nil),
		(*UiPacket_InitialPetRequest)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_packets_proto_rawDesc), len(file_shared_packets_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shared_packets_proto_goTypes,
		DependencyIndexes: file_shared_packets_proto_depIdxs,
		MessageInfos:      file_shared_packets_proto_msgTypes,
	}.Build()
	File_shared_packets_proto = out.File
	file_shared_packets_proto_goTypes = nil
	file_shared_packets_proto_depIdxs = nil
}
